apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: name
      app.kubernetes.io/component: component
  template:
    metadata:
      name: {{ .Release.Name }}-backend
      labels:
        app.kubernetes.io/name: name
        app.kubernetes.io/component: component
    spec:
      containers:
      - image: {{ .Values.deployment.image }}
        name: {{ .Release.Name }}-backend
        ports:
        - containerPort: {{ .Values.deployment.config.port }}
          protocol: TCP