apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: name
    app.kubernetes.io/component: component
  ports:
    - port: 80
      targetPort: {{ .Values.deployment.config.port }}
      protocol: TCP
      name: http
